version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    command: python app.py
    environment:
      - MONGO_URI=mongodb://mongo:27017/blockvault
      - FLASK_ENV=development
      - SECRET_KEY=change-me-compose
      - JWT_SECRET=change-me-jwt-compose
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - storage_data:/app/storage
volumes:
  mongo_data:
  storage_data:
