services:
  - type: web
    name: blockvault-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: blockvault-mongo
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

databases:
  - name: blockvault-mongo
    databaseName: blockvault
    user: blockvault
